name: Reusable Workflow Caller

on:
  workflow_dispatch:

jobs:
  Reusable-caller-job:
    uses: ./.github/workflows/maven-cache.yml
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
